return {

}

-- return {
--     "nvim-tree/nvim-tree.lua",
--     dependencies = "nvim-tree/nvim-web-devicons",
--     config = function()
--         local nvimtree = require("nvim-tree")
-- 
--         -- recommended settings nvimtree doc
--         vim.g.loaded_netrw = 1
--         vim.g.loaded_netrwPlugin = 1
-- 
--         nvimtree.setup({
--             view = {
--                 width = 35,
--                 relativenumber = true,
--             },
-- 
--             -- change folder arrow icon
--             renderer = {
--                 indent_markers = {
--                     enable = true,
--                 },
--                 icons = {
--                     glyphs = {
--                         folder = {
--                             arrow_closed = "→", -- arrow when folder is closed
--                             arrow_open = "↓", -- arrow when folder is open
--                         },
--                     },
--                 },
--             },
-- 
--             -- disable window_picker for build in functionality and window splits
--             actions = {
--                 open_file = {
--                     window_picker = {
--                         enable = false,
--                     },
--                 },
--             },
--             filters = {
--                 custom = { ".DS_Store" },
--             },
--             git = {
--                 ignore = false,
--             },
--         })
-- 
--         -- set keymaps
--         vim.keymap.set("n", "<leader>ee", "<cmd>NvimTreeToggle<CR>") -- toggle file explorer
--         vim.keymap.set("n", "<leader>ef", "<cmd>NvimTreeFindFile<CR>") -- toggle file explorer on current window
--         vim.keymap.set("n", "<leader>ec", "<cmd>NvimTreeCollapse<CR>") -- collapse file explorer
--         vim.keymap.set("n", "<leader>er", "<cmd>NvimTreeRefresh<CR>") -- refresh file explorer
--     end
-- }
